package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"time"

	"github.com/chwarner-solo/grimoire/grimoire-api/internal/generated"
	"github.com/chwarner-solo/grimoire/grimoire-api/internal/middleware"
	"github.com/chwarner-solo/grimoire/grimoire-api/internal/model"
	campaigninteractor "github.com/chwarner-solo/grimoire/grimoire-domain/roots/campaign/interactor"
	"github.com/chwarner-solo/grimoire/grimoire-domain/shared/event"
	"github.com/chwarner-solo/grimoire/grimoire-domain/shared/identity"
)

// CreateCampaign is the resolver for the createCampaign field.
func (r *mutationResolver) CreateCampaign(ctx context.Context, input generated.CreateCampaignInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	result, err := r.createCampaign.Execute(ctx, campaigninteractor.CreateCampaignRequest{
		CallerID:   callerID,
		CampaignID: identity.NewCampaignID(),
		GameID:     gameID,
		Name:       input.Name,
		Source:     event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	snap := result.Campaign.Snapshot()
	return &model.MutationResult{ID: snap.ID.String(), Status: snap.State}, nil
}

// AddCharacterToCampaign is the resolver for the addCharacterToCampaign field.
func (r *mutationResolver) AddCharacterToCampaign(ctx context.Context, input generated.AddCharacterToCampaignInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	campaignID, err := identity.ParseCampaignID(input.CampaignID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	characterID, err := identity.ParsePlayerCharacterID(input.CharacterID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	result, err := r.addCharacterToCampaign.Execute(ctx, campaigninteractor.AddCharacterToCampaignRequest{
		CallerID:    callerID,
		CampaignID:  campaignID,
		GameID:      gameID,
		CharacterID: characterID,
		Source:      event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	snap := result.Campaign.Snapshot()
	return &model.MutationResult{ID: snap.ID.String(), Status: snap.State}, nil
}

// BeginCampaignFormation is the resolver for the beginCampaignFormation field.
func (r *mutationResolver) BeginCampaignFormation(ctx context.Context, input generated.BeginCampaignFormationInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	campaignID, err := identity.ParseCampaignID(input.CampaignID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	result, err := r.beginCampaignFormation.Execute(ctx, campaigninteractor.BeginCampaignFormationRequest{
		CallerID:   callerID,
		CampaignID: campaignID,
		GameID:     gameID,
		Source:     event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	snap := result.Campaign.Snapshot()
	return &model.MutationResult{ID: snap.ID.String(), Status: snap.State}, nil
}

// StartFirstSession is the resolver for the startFirstSession field.
func (r *mutationResolver) StartFirstSession(ctx context.Context, input generated.StartFirstSessionInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	campaignID, err := identity.ParseCampaignID(input.CampaignID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	date, err := time.Parse("2006-01-02", input.Date)
	if err != nil {
		return nil, &errInvalidInput{field: "date", reason: "must be ISO 8601 date (YYYY-MM-DD)"}
	}
	result, err := r.startFirstSession.Execute(ctx, campaigninteractor.StartFirstSessionRequest{
		CallerID:   callerID,
		CampaignID: campaignID,
		GameID:     gameID,
		SessionID:  identity.NewSessionID(),
		Date:       date,
		Source:     event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	snap := result.Campaign.Snapshot()
	return &model.MutationResult{ID: snap.ID.String(), Status: snap.State}, nil
}

// StartNewSession is the resolver for the startNewSession field.
func (r *mutationResolver) StartNewSession(ctx context.Context, input generated.StartNewSessionInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	campaignID, err := identity.ParseCampaignID(input.CampaignID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	date, err := time.Parse("2006-01-02", input.Date)
	if err != nil {
		return nil, &errInvalidInput{field: "date", reason: "must be ISO 8601 date (YYYY-MM-DD)"}
	}
	result, err := r.startNewSession.Execute(ctx, campaigninteractor.StartNewSessionRequest{
		CallerID:   callerID,
		CampaignID: campaignID,
		GameID:     gameID,
		SessionID:  identity.NewSessionID(),
		Date:       date,
		Source:     event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	snap := result.Campaign.Snapshot()
	return &model.MutationResult{ID: snap.ID.String(), Status: snap.State}, nil
}

// EndSession is the resolver for the endSession field.
func (r *mutationResolver) EndSession(ctx context.Context, input generated.EndSessionInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	campaignID, err := identity.ParseCampaignID(input.CampaignID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	sessionID, err := identity.ParseSessionID(input.SessionID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	notes := ""
	if input.Notes != nil {
		notes = *input.Notes
	}
	result, err := r.endSession.Execute(ctx, campaigninteractor.EndSessionRequest{
		CallerID:   callerID,
		CampaignID: campaignID,
		GameID:     gameID,
		SessionID:  sessionID,
		Notes:      notes,
		Source:     event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	snap := result.Campaign.Snapshot()
	return &model.MutationResult{ID: snap.ID.String(), Status: snap.State}, nil
}

// MoveParty is the resolver for the moveParty field.
func (r *mutationResolver) MoveParty(ctx context.Context, input generated.MovePartyInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	campaignID, err := identity.ParseCampaignID(input.CampaignID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	locationID, err := identity.ParseLocationID(input.LocationID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	result, err := r.moveParty.Execute(ctx, campaigninteractor.MovePartyRequest{
		CallerID:   callerID,
		CampaignID: campaignID,
		GameID:     gameID,
		LocationID: locationID,
		Source:     event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	snap := result.Campaign.Snapshot()
	return &model.MutationResult{ID: snap.ID.String(), Status: snap.State}, nil
}

// CompleteCampaign is the resolver for the completeCampaign field.
func (r *mutationResolver) CompleteCampaign(ctx context.Context, input generated.CompleteCampaignInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	campaignID, err := identity.ParseCampaignID(input.CampaignID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	result, err := r.completeCampaign.Execute(ctx, campaigninteractor.CompleteCampaignRequest{
		CallerID:   callerID,
		CampaignID: campaignID,
		GameID:     gameID,
		Source:     event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	snap := result.Campaign.Snapshot()
	return &model.MutationResult{ID: snap.ID.String(), Status: snap.State}, nil
}
