package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/chwarner-solo/grimoire/grimoire-api/internal/generated"
	"github.com/chwarner-solo/grimoire/grimoire-api/internal/middleware"
	"github.com/chwarner-solo/grimoire/grimoire-api/internal/model"
	characterinteractor "github.com/chwarner-solo/grimoire/grimoire-domain/roots/character/interactor"
	"github.com/chwarner-solo/grimoire/grimoire-domain/shared/event"
	"github.com/chwarner-solo/grimoire/grimoire-domain/shared/identity"
)

// CreateNpc is the resolver for the createNPC field.
func (r *mutationResolver) CreateNpc(ctx context.Context, input generated.CreateNPCInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	result, err := r.createNPC.Execute(ctx, characterinteractor.CreateNPCRequest{
		CallerID: callerID,
		ID:       identity.NewNarrativeCharacterID(),
		GameID:   gameID,
		Name:     input.Name,
		Source:   event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	snap := result.NPC.Snapshot()
	return &model.MutationResult{ID: snap.ID.String(), Status: snap.State}, nil
}

// BeginNPCDraft is the resolver for the beginNPCDraft field.
func (r *mutationResolver) BeginNPCDraft(ctx context.Context, input generated.NPCLifecycleInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	npcID, err := identity.ParseNarrativeCharacterID(input.NpcID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	result, err := r.beginNPCDraft.Execute(ctx, characterinteractor.BeginNPCDraftRequest{
		CallerID: callerID,
		NPCID:    npcID,
		GameID:   gameID,
		Source:   event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	snap := result.NPC.Snapshot()
	return &model.MutationResult{ID: snap.ID.String(), Status: snap.State}, nil
}

// UpdateNPCContent is the resolver for the updateNPCContent field.
func (r *mutationResolver) UpdateNPCContent(ctx context.Context, input generated.UpdateNPCContentInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	npcID, err := identity.ParseNarrativeCharacterID(input.NpcID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	result, err := r.updateNPCContent.Execute(ctx, characterinteractor.UpdateNPCContentRequest{
		CallerID:    callerID,
		NPCID:       npcID,
		GameID:      gameID,
		Name:        input.Name,
		Description: input.Description,
		PlayerDesc:  input.PlayerDesc,
		Source:      event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	snap := result.NPC.Snapshot()
	return &model.MutationResult{ID: snap.ID.String(), Status: snap.State}, nil
}

// ActivateNpc is the resolver for the activateNPC field.
func (r *mutationResolver) ActivateNpc(ctx context.Context, input generated.NPCLifecycleInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	npcID, err := identity.ParseNarrativeCharacterID(input.NpcID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	result, err := r.activateNPC.Execute(ctx, characterinteractor.ActivateNPCRequest{
		CallerID: callerID,
		NPCID:    npcID,
		GameID:   gameID,
		Source:   event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	snap := result.NPC.Snapshot()
	return &model.MutationResult{ID: snap.ID.String(), Status: snap.State}, nil
}

// ArchiveNpc is the resolver for the archiveNPC field.
func (r *mutationResolver) ArchiveNpc(ctx context.Context, input generated.NPCLifecycleInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	npcID, err := identity.ParseNarrativeCharacterID(input.NpcID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	result, err := r.archiveNPC.Execute(ctx, characterinteractor.ArchiveNPCRequest{
		CallerID: callerID,
		NPCID:    npcID,
		GameID:   gameID,
		Source:   event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	snap := result.NPC.Snapshot()
	return &model.MutationResult{ID: snap.ID.String(), Status: snap.State}, nil
}

// CreatePlayerCharacter is the resolver for the createPlayerCharacter field.
func (r *mutationResolver) CreatePlayerCharacter(ctx context.Context, input generated.CreatePlayerCharacterInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	ownerPlayerID := ""
	if input.OwnerPlayerID != nil {
		ownerPlayerID = *input.OwnerPlayerID
	}
	result, err := r.createPlayerCharacter.Execute(ctx, characterinteractor.CreatePlayerCharacterRequest{
		CallerID:      callerID,
		ID:            identity.NewPlayerCharacterID(),
		GameID:        gameID,
		Name:          input.Name,
		OwnerPlayerID: ownerPlayerID,
		Source:        event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	snap := result.PlayerCharacter.Snapshot()
	return &model.MutationResult{ID: snap.ID.String(), Status: string(snap.Status)}, nil
}

// UpdatePlayerCharacterContent is the resolver for the updatePlayerCharacterContent field.
func (r *mutationResolver) UpdatePlayerCharacterContent(ctx context.Context, input generated.UpdatePCContentInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	characterID, err := identity.ParsePlayerCharacterID(input.CharacterID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	result, err := r.updatePlayerCharacterContent.Execute(ctx, characterinteractor.UpdatePlayerCharacterContentRequest{
		CallerID:    callerID,
		ID:          characterID,
		GameID:      gameID,
		Name:        input.Name,
		Description: input.Description,
		PlayerDesc:  input.PlayerDesc,
		Source:      event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	snap := result.PlayerCharacter.Snapshot()
	return &model.MutationResult{ID: snap.ID.String(), Status: string(snap.Status)}, nil
}

// RetirePlayerCharacter is the resolver for the retirePlayerCharacter field.
func (r *mutationResolver) RetirePlayerCharacter(ctx context.Context, input generated.PCLifecycleInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	characterID, err := identity.ParsePlayerCharacterID(input.CharacterID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	result, err := r.retirePlayerCharacter.Execute(ctx, characterinteractor.RetirePlayerCharacterRequest{
		CallerID: callerID,
		ID:       characterID,
		GameID:   gameID,
		Source:   event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	snap := result.PlayerCharacter.Snapshot()
	return &model.MutationResult{ID: snap.ID.String(), Status: string(snap.Status)}, nil
}

// CreateMacGuffin is the resolver for the createMacGuffin field.
func (r *mutationResolver) CreateMacGuffin(ctx context.Context, input generated.CreateMacGuffinInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	result, err := r.createMacGuffin.Execute(ctx, characterinteractor.CreateMacGuffinRequest{
		CallerID: callerID,
		ID:       identity.NewMacGuffinID(),
		GameID:   gameID,
		Name:     input.Name,
		Source:   event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	status := "active"
	if result.MacGuffin.IsDestroyed() {
		status = "destroyed"
	}
	return &model.MutationResult{ID: result.MacGuffin.MacGuffinID().String(), Status: status}, nil
}

// UpdateMacGuffinContent is the resolver for the updateMacGuffinContent field.
func (r *mutationResolver) UpdateMacGuffinContent(ctx context.Context, input generated.UpdateMacGuffinContentInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	macGuffinID, err := identity.ParseMacGuffinID(input.MacGuffinID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	_, err = r.updateMacGuffinContent.Execute(ctx, characterinteractor.UpdateMacGuffinContentRequest{
		CallerID:    callerID,
		MacGuffinID: macGuffinID,
		GameID:      gameID,
		Name:        input.Name,
		Description: input.Description,
		PlayerDesc:  input.PlayerDesc,
		Source:      event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return &model.MutationResult{ID: macGuffinID.String(), Status: "updated"}, nil
}

// AssignMacGuffinToNpc is the resolver for the assignMacGuffinToNPC field.
func (r *mutationResolver) AssignMacGuffinToNpc(ctx context.Context, input generated.AssignMacGuffinToNPCInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	macGuffinID, err := identity.ParseMacGuffinID(input.MacGuffinID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	npcID, err := identity.ParseNarrativeCharacterID(input.NpcID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	_, err = r.assignMacGuffinToNPC.Execute(ctx, characterinteractor.AssignMacGuffinToNPCRequest{
		CallerID:    callerID,
		MacGuffinID: macGuffinID,
		NPCID:       npcID,
		GameID:      gameID,
		Source:      event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return &model.MutationResult{ID: macGuffinID.String(), Status: "assigned"}, nil
}

// AssignMacGuffinToPc is the resolver for the assignMacGuffinToPC field.
func (r *mutationResolver) AssignMacGuffinToPc(ctx context.Context, input generated.AssignMacGuffinToPCInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	macGuffinID, err := identity.ParseMacGuffinID(input.MacGuffinID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	characterID, err := identity.ParsePlayerCharacterID(input.CharacterID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	_, err = r.assignMacGuffinToPC.Execute(ctx, characterinteractor.AssignMacGuffinToPCRequest{
		CallerID:    callerID,
		MacGuffinID: macGuffinID,
		PCID:        characterID,
		GameID:      gameID,
		Source:      event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return &model.MutationResult{ID: macGuffinID.String(), Status: "assigned"}, nil
}

// DestroyMacGuffin is the resolver for the destroyMacGuffin field.
func (r *mutationResolver) DestroyMacGuffin(ctx context.Context, input generated.MacGuffinLifecycleInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	macGuffinID, err := identity.ParseMacGuffinID(input.MacGuffinID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	_, err = r.destroyMacGuffin.Execute(ctx, characterinteractor.DestroyMacGuffinRequest{
		CallerID:    callerID,
		MacGuffinID: macGuffinID,
		GameID:      gameID,
		Source:      event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return &model.MutationResult{ID: macGuffinID.String(), Status: "destroyed"}, nil
}
