package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/chwarner-solo/grimoire/grimoire-api/internal/generated"
	"github.com/chwarner-solo/grimoire/grimoire-api/internal/middleware"
	"github.com/chwarner-solo/grimoire/grimoire-api/internal/model"
	factioninteractor "github.com/chwarner-solo/grimoire/grimoire-domain/roots/faction/interactor"
	factionvalue "github.com/chwarner-solo/grimoire/grimoire-domain/roots/faction/value"
	"github.com/chwarner-solo/grimoire/grimoire-domain/shared/event"
	"github.com/chwarner-solo/grimoire/grimoire-domain/shared/identity"
)

// CreateFaction is the resolver for the createFaction field.
func (r *mutationResolver) CreateFaction(ctx context.Context, input generated.CreateFactionInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	result, err := r.createFaction.Execute(ctx, factioninteractor.CreateFactionRequest{
		CallerID: callerID,
		ID:       identity.NewFactionID(),
		GameID:   gameID,
		Name:     input.Name,
		Source:   event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	snap := result.Faction.Snapshot()
	return &model.MutationResult{ID: snap.ID.String(), Status: snap.State}, nil
}

// BeginFactionDraft is the resolver for the beginFactionDraft field.
func (r *mutationResolver) BeginFactionDraft(ctx context.Context, input generated.FactionLifecycleInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	factionID, err := identity.ParseFactionID(input.FactionID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	result, err := r.beginFactionDraft.Execute(ctx, factioninteractor.BeginFactionDraftRequest{
		CallerID:  callerID,
		FactionID: factionID,
		GameID:    gameID,
		Source:    event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	snap := result.Faction.Snapshot()
	return &model.MutationResult{ID: snap.ID.String(), Status: snap.State}, nil
}

// ActivateFaction is the resolver for the activateFaction field.
func (r *mutationResolver) ActivateFaction(ctx context.Context, input generated.FactionLifecycleInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	factionID, err := identity.ParseFactionID(input.FactionID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	result, err := r.activateFaction.Execute(ctx, factioninteractor.ActivateFactionRequest{
		CallerID:  callerID,
		FactionID: factionID,
		GameID:    gameID,
		Source:    event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	snap := result.Faction.Snapshot()
	return &model.MutationResult{ID: snap.ID.String(), Status: snap.State}, nil
}

// AddFactionMember is the resolver for the addFactionMember field.
func (r *mutationResolver) AddFactionMember(ctx context.Context, input generated.AddFactionMemberInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	factionID, err := identity.ParseFactionID(input.FactionID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	npcID, err := identity.ParseNarrativeCharacterID(input.NpcID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	_, err = r.addFactionMember.Execute(ctx, factioninteractor.AddFactionMemberRequest{
		CallerID:     callerID,
		FactionID:    factionID,
		MembershipID: identity.NewFactionMembershipID(),
		NPCID:        npcID,
		Rank:         input.Rank,
		GameID:       gameID,
		Source:       event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return &model.MutationResult{ID: factionID.String(), Status: "updated"}, nil
}

// AddStandingLevel is the resolver for the addStandingLevel field.
func (r *mutationResolver) AddStandingLevel(ctx context.Context, input generated.AddStandingLevelInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	factionID, err := identity.ParseFactionID(input.FactionID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	level, err := factionvalue.NewStandingLevel(input.Name, input.Threshold, input.Ordinal)
	if err != nil {
		return nil, mapDomainError(err)
	}
	_, err = r.addStandingLevel.Execute(ctx, factioninteractor.AddStandingLevelRequest{
		CallerID:  callerID,
		FactionID: factionID,
		GameID:    gameID,
		Level:     level,
		Source:    event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return &model.MutationResult{ID: factionID.String(), Status: "updated"}, nil
}

// DeclareAlly is the resolver for the declareAlly field.
func (r *mutationResolver) DeclareAlly(ctx context.Context, input generated.FactionRelationshipInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	factionID, err := identity.ParseFactionID(input.FactionID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	allyID, err := identity.ParseFactionID(input.TargetID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	_, err = r.declareAlly.Execute(ctx, factioninteractor.DeclareAllyRequest{
		CallerID:  callerID,
		FactionID: factionID,
		AllyID:    allyID,
		GameID:    gameID,
		Source:    event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return &model.MutationResult{ID: factionID.String(), Status: "updated"}, nil
}

// DeclareWar is the resolver for the declareWar field.
func (r *mutationResolver) DeclareWar(ctx context.Context, input generated.FactionRelationshipInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	factionID, err := identity.ParseFactionID(input.FactionID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	enemyID, err := identity.ParseFactionID(input.TargetID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	_, err = r.declareWar.Execute(ctx, factioninteractor.DeclareWarRequest{
		CallerID:  callerID,
		FactionID: factionID,
		EnemyID:   enemyID,
		GameID:    gameID,
		Source:    event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return &model.MutationResult{ID: factionID.String(), Status: "updated"}, nil
}

// MarkFactionDormant is the resolver for the markFactionDormant field.
func (r *mutationResolver) MarkFactionDormant(ctx context.Context, input generated.FactionLifecycleInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	factionID, err := identity.ParseFactionID(input.FactionID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	result, err := r.markFactionDormant.Execute(ctx, factioninteractor.MarkFactionDormantRequest{
		CallerID:  callerID,
		FactionID: factionID,
		GameID:    gameID,
		Source:    event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	snap := result.Faction.Snapshot()
	return &model.MutationResult{ID: snap.ID.String(), Status: snap.State}, nil
}

// ReactivateFaction is the resolver for the reactivateFaction field.
func (r *mutationResolver) ReactivateFaction(ctx context.Context, input generated.FactionLifecycleInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	factionID, err := identity.ParseFactionID(input.FactionID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	result, err := r.reactivateFaction.Execute(ctx, factioninteractor.ReactivateFactionRequest{
		CallerID:  callerID,
		FactionID: factionID,
		GameID:    gameID,
		Source:    event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	snap := result.Faction.Snapshot()
	return &model.MutationResult{ID: snap.ID.String(), Status: snap.State}, nil
}

// ArchiveFaction is the resolver for the archiveFaction field.
func (r *mutationResolver) ArchiveFaction(ctx context.Context, input generated.FactionLifecycleInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	factionID, err := identity.ParseFactionID(input.FactionID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	result, err := r.archiveFaction.Execute(ctx, factioninteractor.ArchiveFactionRequest{
		CallerID:  callerID,
		FactionID: factionID,
		GameID:    gameID,
		Source:    event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	snap := result.Faction.Snapshot()
	return &model.MutationResult{ID: snap.ID.String(), Status: snap.State}, nil
}
