package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/chwarner-solo/grimoire/grimoire-api/internal/generated"
	"github.com/chwarner-solo/grimoire/grimoire-api/internal/middleware"
	"github.com/chwarner-solo/grimoire/grimoire-api/internal/model"
	gameinteractor "github.com/chwarner-solo/grimoire/grimoire-domain/roots/game/interactor"
	"github.com/chwarner-solo/grimoire/grimoire-domain/shared/event"
	"github.com/chwarner-solo/grimoire/grimoire-domain/shared/identity"
)

// CreateGame is the resolver for the createGame field.
func (r *mutationResolver) CreateGame(ctx context.Context, input generated.CreateGameInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	result, err := r.createGame.Execute(ctx, gameinteractor.CreateGameRequest{
		CallerID: callerID,
		ID:       identity.NewGameID(),
		Name:     input.Name,
		Source:   event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	snap := result.Game.Snapshot()
	return &model.MutationResult{ID: snap.ID.String(), Status: snap.State}, nil
}

// ArchiveGame is the resolver for the archiveGame field.
func (r *mutationResolver) ArchiveGame(ctx context.Context, input generated.ArchiveGameInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	result, err := r.archiveGame.Execute(ctx, gameinteractor.ArchiveGameRequest{
		CallerID: callerID,
		GameID:   gameID,
		Source:   event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	snap := result.Game.Snapshot()
	return &model.MutationResult{ID: snap.ID.String(), Status: snap.State}, nil
}
