package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"strings"

	"github.com/chwarner-solo/grimoire/grimoire-api/internal/generated"
	"github.com/chwarner-solo/grimoire/grimoire-api/internal/middleware"
	"github.com/chwarner-solo/grimoire/grimoire-api/internal/model"
	locationinteractor "github.com/chwarner-solo/grimoire/grimoire-domain/roots/location/interactor"
	locationvalue "github.com/chwarner-solo/grimoire/grimoire-domain/roots/location/value"
	"github.com/chwarner-solo/grimoire/grimoire-domain/shared/event"
	"github.com/chwarner-solo/grimoire/grimoire-domain/shared/identity"
)

// CreateLocation is the resolver for the createLocation field.
func (r *mutationResolver) CreateLocation(ctx context.Context, input generated.CreateLocationInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	req := locationinteractor.CreateLocationRequest{
		CallerID:     callerID,
		ID:           identity.NewLocationID(),
		GameID:       gameID,
		Name:         input.Name,
		LocationType: locationvalue.LocationType(strings.ToLower(string(input.LocationType))),
		Source:       event.SourceGrimoire,
	}
	if input.ParentID != nil {
		parentID, err := identity.ParseLocationID(*input.ParentID)
		if err != nil {
			return nil, mapDomainError(err)
		}
		req.ParentID = parentID
	}
	result, err := r.createLocation.Execute(ctx, req)
	if err != nil {
		return nil, mapDomainError(err)
	}
	snap := result.Location.Snapshot()
	return &model.MutationResult{ID: snap.ID.String(), Status: snap.State}, nil
}

// ActivateLocation is the resolver for the activateLocation field.
func (r *mutationResolver) ActivateLocation(ctx context.Context, input generated.LocationLifecycleInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	locationID, err := identity.ParseLocationID(input.LocationID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	result, err := r.activateLocation.Execute(ctx, locationinteractor.ActivateLocationRequest{
		CallerID:   callerID,
		LocationID: locationID,
		GameID:     gameID,
		Source:     event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	snap := result.Location.Snapshot()
	return &model.MutationResult{ID: snap.ID.String(), Status: snap.State}, nil
}

// AddScene is the resolver for the addScene field.
func (r *mutationResolver) AddScene(ctx context.Context, input generated.AddSceneInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	locationID, err := identity.ParseLocationID(input.LocationID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	_, err = r.addScene.Execute(ctx, locationinteractor.AddSceneRequest{
		CallerID:   callerID,
		LocationID: locationID,
		SceneID:    identity.NewSceneID(),
		GameID:     gameID,
		Name:       input.Name,
		Source:     event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return &model.MutationResult{ID: locationID.String(), Status: "updated"}, nil
}

// ConnectLocations is the resolver for the connectLocations field.
func (r *mutationResolver) ConnectLocations(ctx context.Context, input generated.ConnectLocationsInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	fromID, err := identity.ParseLocationID(input.FromID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	toID, err := identity.ParseLocationID(input.ToID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	_, err = r.connectLocations.Execute(ctx, locationinteractor.ConnectLocationsRequest{
		CallerID: callerID,
		FromID:   fromID,
		ToID:     toID,
		GameID:   gameID,
		Source:   event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return &model.MutationResult{ID: fromID.String(), Status: "connected"}, nil
}

// ArchiveLocation is the resolver for the archiveLocation field.
func (r *mutationResolver) ArchiveLocation(ctx context.Context, input generated.LocationLifecycleInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	locationID, err := identity.ParseLocationID(input.LocationID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	result, err := r.archiveLocation.Execute(ctx, locationinteractor.ArchiveLocationRequest{
		CallerID:   callerID,
		LocationID: locationID,
		GameID:     gameID,
		Source:     event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	snap := result.Location.Snapshot()
	return &model.MutationResult{ID: snap.ID.String(), Status: snap.State}, nil
}
