package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/chwarner-solo/grimoire/grimoire-api/internal/generated"
	"github.com/chwarner-solo/grimoire/grimoire-api/internal/middleware"
	"github.com/chwarner-solo/grimoire/grimoire-api/internal/model"
	narrativeinteractor "github.com/chwarner-solo/grimoire/grimoire-domain/roots/narrative/interactor"
	narrativevalue "github.com/chwarner-solo/grimoire/grimoire-domain/roots/narrative/value"
	"github.com/chwarner-solo/grimoire/grimoire-domain/shared/event"
	"github.com/chwarner-solo/grimoire/grimoire-domain/shared/identity"
)

// CreateMasterBeat is the resolver for the createMasterBeat field.
func (r *mutationResolver) CreateMasterBeat(ctx context.Context, input generated.CreateMasterBeatInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	result, err := r.createMasterBeat.Execute(ctx, narrativeinteractor.CreateMasterBeatRequest{
		CallerID: callerID,
		BeatID:   identity.NewBeatID(),
		GameID:   gameID,
		Name:     input.Name,
		BeatType: mapBeatType(input.BeatType),
		Source:   event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	snap := result.Beat.Snapshot()
	return &model.MutationResult{ID: snap.ID.String(), Status: string(snap.Status)}, nil
}

// UpdateBeatContent is the resolver for the updateBeatContent field.
func (r *mutationResolver) UpdateBeatContent(ctx context.Context, input generated.UpdateBeatContentInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	beatID, err := identity.ParseBeatID(input.BeatID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	result, err := r.updateBeatContent.Execute(ctx, narrativeinteractor.UpdateBeatContentRequest{
		CallerID:    callerID,
		BeatID:      beatID,
		GameID:      gameID,
		Name:        input.Name,
		Description: input.Description,
		PlayerDesc:  input.PlayerDesc,
		Source:      event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	snap := result.Beat.Snapshot()
	return &model.MutationResult{ID: snap.ID.String(), Status: string(snap.Status)}, nil
}

// AddBeatPrerequisite is the resolver for the addBeatPrerequisite field.
func (r *mutationResolver) AddBeatPrerequisite(ctx context.Context, input generated.AddBeatPrerequisiteInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	beatID, err := identity.ParseBeatID(input.BeatID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	prereqID, err := identity.ParseBeatID(input.PrerequisiteID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	result, err := r.addBeatPrerequisite.Execute(ctx, narrativeinteractor.AddBeatPrerequisiteRequest{
		CallerID:       callerID,
		BeatID:         beatID,
		PrerequisiteID: prereqID,
		GameID:         gameID,
		Source:         event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	snap := result.Beat.Snapshot()
	return &model.MutationResult{ID: snap.ID.String(), Status: string(snap.Status)}, nil
}

// AddActToMasterNarrative is the resolver for the addActToMasterNarrative field.
func (r *mutationResolver) AddActToMasterNarrative(ctx context.Context, input generated.AddActInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	actID, err := identity.ParseActID(input.ActID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	_, err = r.addActToMasterNarrative.Execute(ctx, narrativeinteractor.AddActToMasterNarrativeRequest{
		CallerID: callerID,
		ActID:    actID,
		GameID:   gameID,
		Source:   event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return &model.MutationResult{ID: actID.String(), Status: "linked"}, nil
}

// AddSecretToMasterNarrative is the resolver for the addSecretToMasterNarrative field.
func (r *mutationResolver) AddSecretToMasterNarrative(ctx context.Context, input generated.AddSecretInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	secretID, err := identity.ParseSecretID(input.SecretID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	_, err = r.addSecretToMasterNarrative.Execute(ctx, narrativeinteractor.AddSecretToMasterNarrativeRequest{
		CallerID: callerID,
		SecretID: secretID,
		GameID:   gameID,
		Source:   event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return &model.MutationResult{ID: secretID.String(), Status: "linked"}, nil
}

// AddLoreToMasterNarrative is the resolver for the addLoreToMasterNarrative field.
func (r *mutationResolver) AddLoreToMasterNarrative(ctx context.Context, input generated.AddLoreInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	loreID, err := identity.ParseLoreID(input.LoreID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	_, err = r.addLoreToMasterNarrative.Execute(ctx, narrativeinteractor.AddLoreToMasterNarrativeRequest{
		CallerID: callerID,
		LoreID:   loreID,
		GameID:   gameID,
		Source:   event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return &model.MutationResult{ID: loreID.String(), Status: "linked"}, nil
}

// DiscoverBeat is the resolver for the discoverBeat field.
func (r *mutationResolver) DiscoverBeat(ctx context.Context, input generated.DiscoverBeatInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	cnID, err := identity.ParseCampaignNarrativeID(input.CampaignNarrativeID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	beatID, err := identity.ParseBeatID(input.BeatID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	_, err = r.discoverBeat.Execute(ctx, narrativeinteractor.DiscoverBeatRequest{
		CallerID:            callerID,
		CampaignNarrativeID: cnID,
		BeatID:              beatID,
		GameID:              gameID,
		Source:              event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return &model.MutationResult{ID: beatID.String(), Status: "discovered"}, nil
}

// CreateCampaignBeat is the resolver for the createCampaignBeat field.
func (r *mutationResolver) CreateCampaignBeat(ctx context.Context, input generated.CreateCampaignBeatInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	campaignID, err := identity.ParseCampaignID(input.CampaignID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	result, err := r.createCampaignBeat.Execute(ctx, narrativeinteractor.CreateCampaignBeatRequest{
		CallerID:   callerID,
		BeatID:     identity.NewBeatID(),
		CampaignID: campaignID,
		GameID:     gameID,
		Name:       input.Name,
		Source:     event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	snap := result.Beat.Snapshot()
	return &model.MutationResult{ID: snap.ID.String(), Status: string(snap.Status)}, nil
}

// PromoteBeatToMaster is the resolver for the promoteBeatToMaster field.
func (r *mutationResolver) PromoteBeatToMaster(ctx context.Context, input generated.PromoteBeatInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	beatID, err := identity.ParseBeatID(input.BeatID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	result, err := r.promoteBeatToMaster.Execute(ctx, narrativeinteractor.PromoteBeatToMasterRequest{
		CallerID: callerID,
		BeatID:   beatID,
		GameID:   gameID,
		Source:   event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	snap := result.Beat.Snapshot()
	return &model.MutationResult{ID: snap.ID.String(), Status: string(snap.Status)}, nil
}

func mapBeatType(bt generated.BeatType) narrativevalue.BeatType {
	switch bt {
	case generated.BeatTypeRequired:
		return narrativevalue.BeatTypeRequired
	case generated.BeatTypeOptional:
		return narrativevalue.BeatTypeOptional
	case generated.BeatTypeCampaignSpecific:
		return narrativevalue.BeatTypeCampaignSpecific
	default:
		return narrativevalue.BeatTypeRequired
	}
}
