package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/chwarner-solo/grimoire/grimoire-api/internal/generated"
	"github.com/chwarner-solo/grimoire/grimoire-api/internal/middleware"
	"github.com/chwarner-solo/grimoire/grimoire-api/internal/model"
	sharedinteractor "github.com/chwarner-solo/grimoire/grimoire-domain/shared/interactor"
	"github.com/chwarner-solo/grimoire/grimoire-domain/shared/event"
	"github.com/chwarner-solo/grimoire/grimoire-domain/shared/identity"
	"github.com/chwarner-solo/grimoire/grimoire-domain/shared/value"
)

// RevealEntity is the resolver for the revealEntity field.
func (r *mutationResolver) RevealEntity(ctx context.Context, input generated.RevealEntityInput) (*model.MutationResult, error) {
	callerID, err := r.auth.Identify(ctx, middleware.TokenFromContext(ctx))
	if err != nil {
		return nil, errUnauthenticated
	}
	gameID, err := identity.ParseGameID(input.GameID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	sessionID, err := identity.ParseSessionID(input.SessionID)
	if err != nil {
		return nil, mapDomainError(err)
	}
	_, err = r.revealEntity.Execute(ctx, sharedinteractor.RevealEntityRequest{
		CallerID:   callerID,
		EntityID:   input.EntityID,
		EntityType: mapEntityType(input.EntityType),
		GameID:     gameID,
		RevealedTo: input.RevealedTo,
		SessionID:  sessionID,
		Source:     event.SourceGrimoire,
	})
	if err != nil {
		return nil, mapDomainError(err)
	}
	return &model.MutationResult{ID: input.EntityID, Status: "revealed"}, nil
}

func mapEntityType(et generated.RevealableEntityType) value.EntityType {
	switch et {
	case generated.RevealableEntityTypeNpc:
		return value.EntityTypeNPC
	case generated.RevealableEntityTypePlayerCharacter:
		return value.EntityTypePlayerCharacter
	case generated.RevealableEntityTypeMacguffin:
		return value.EntityTypeMacGuffin
	case generated.RevealableEntityTypeFaction:
		return value.EntityTypeFaction
	default:
		return value.EntityTypeNPC
	}
}
